# syntax=docker/dockerfile:1
FROM quay.io/centerforopenscience/elasticsearch:es6-arm-6.3.1

USER root
RUN mkdir -p /usr/share/elasticsearch/config /var/lib/elasticsearch/plugins \
    && chown -R elastico:elastico /usr/share/elasticsearch /var/lib/elasticsearch

USER elastico
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch analysis-kuromoji \
    && /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch analysis-icu

USER root
